
import Navbar from "@/components/navbar";
import "./globals.css";
import { UserProvider } from "@/context/authProvider";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        <UserProvider>
          {children}
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}
